services:
    _defaults:
        autowire: true
        autoconfigure: true

    numero2\MobileDeAdsBundle\Cron\Cron:
        arguments:
            - '@contao.framework'
            - '@numero2_mobile.listener.import.ad'
